[tool.poetry]
name = "figures"
version = "0.1.0"
description = ""
authors = ["iliakhar <kharchenko_ilia@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.1"
pandas = "^2.2.3"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
